baseurl:             ""

url:                 "https://hack-the-universe.github.io/"


full:                false

style:
  theme:             "original"

organiser:
  name:              "Physical Hacks"
#  full_name:         ""
#  site:              ""


event:
  name:              "Hack The Universe 2019"
  # name_short:        "HackTheU"
  description:       "CMU's inaugural physics hackathon"
  date:              "1st-3rd February"
  location:          "Carnegie Mellon University"
  logosrc:           "images/logo.png"
  logoalt:           "HTU Logo"

  about:
    description:     >
      Hack the Universe is the dankest hackathon on the horizon.

  workshops:
      - name: "Introduction to wowy"
        time: "12.00 - 13.00"
        level: "No prior experience required."
        description: "wanna learn wowy? come thru fam"
      # - name: ""
      #   time: "12.00 - 13.00"
      #   level: ""
      #   description: ""


  sponsors:
    # tier1 is top, anycont is bottom (refer to sponsorship packages)
    tier1:
      - logo:        "/images/gsa_logo.png"
        name:        "CMU Graduate Student Assembly"
        url:         "http://www.cmu.edu/stugov/gsa"
      - logo:        "/images/cmuphysics_logo.png"
        name:        "Physics Department at CMU"
        url:         "http://www.cmu.edu/physics"
    #   - logo:        "images/github_logo.png"
    #     name:        "GitHub"
    #     url:         "https://github.com"
    # tier3:
    #   - logo:        "images/codethink_logo.svg"
    #     name:        "Codethink"
    #     url:         "https://www.codethink.co.uk/"
    # anycont:
    #   - logo:        "images/InformaticsUni_transparent.gif"
    #     name:        "University of Edinburgh School of Informatics"
    #     url:         "http://www.ed.ac.uk/informatics"

  info:
    yo this is the info section what up 

  faq:
    - question:      "What is a hackathon?"
      answer:        >
        A hackathon is an invention marathon. Participants come together to solve interesting problems and create software in the span of a few days.
    - question:      "How much does it cost?"
      answer:        >
        $0. We will also cater all meals for the duration of the event.
    - question:      "Am I eligible to attend"
      answer:        >
        Students at any level, as well as postdocs and faculty members, from any department are welcome to attend. 
    - question:      "I'm a complete beginner. Can I still come?"
      answer:        >
        Absolutely! We especially encourage people that are new in the field to come along as a hackathon is a great place to get started. [Drop us a message](mailto:cameron@ears-edi.com) if you have any concerns.
    - question:      "Where is the event?"
      answer:        >
        The event is being hosted on CMU's campus, in Wean Hall 7316. Teams may also use other rooms on campus, but all major events/catering will happen in 7316
    - question:      "How big are the teams?"
      answer:        >
        There are no restrictions on the number of members in a team.
    - question:      "Do you offer travel reimbursement?"
      answer:        >
        We cannot offer travel reimbursements at this point.
    - question:      "Do I have to come with teammates?"
      answer:        >
        There is a team-forming session at the start of the first day so feel free to come along on your own or with friends.

  schedule:
    Friday:
      - text:        "Start of registration"
        start:       "10:00"
      - text:        "Team forming session 1"
        start:       "10:30"
        end:         "11:00"
    Saturday:
      - text:        "Start of registration"
        start:       "10:00"
      - text:        "Team forming session 1"
        start:       "10:30"
        end:         "11:00"
      - text:        "GitHub workshop"
        start:       "15.00"
        end:         "16.00"
      - text:        "Dinner"
        start:       "18:00"
        end:         "19:00"
    Sunday:
      - text:        "Midnight snack"
        start:       "00:00"
      - text:        "Breakfast"
        start:       "08:00"
        end:         "09:00"
      - text:        "Submissions due"
        start:       "12:00"
      - text:        "Closing ceremony"
        start:       "15:30"
        end:         "16:30"

markdown:            kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
