baseurl:             ""

url:                 "https://hack-the-universe.github.io/"

full:                false

style:
  theme:             "original"

organiser:
  name:              "Physical Hacks"
#  full_name:         ""
#  site:              ""


event:
  name:              "Hack The Universe 2019"
  # name_short:        "HackTheU"
  description:       "CMU's inaugural physics hackathon"
  date:              "1st-3rd February"
  location:          "Carnegie Mellon University"
  logosrc:           "images/logo.png"
  logoalt:           "HTU Logo"

  about:
    description:     >
      a r e  y o u  r e a d y ?

  workshops:
      - name: "Data Visualization"
        time: "Wednesday 23rd Jan, 12.30 - 14.00"
        description: "Learn about data visualization in python using matplotlib, seaborn and plotly."
      - name: "Numerical Methods for and from Physics"
        time: "Tuesday 29th Jan, 16.30 - 18.00"
        description: "Introduction to numerical methods such as Markov Chain Monte Carlo"
      - name: "Machine Learning in Physics"
        time: "Wednesday 30th Jan, 16.30 - 18.00"
        description: "Overview of supervised machine learning techniques and recent applications in physics and astronomy."

  sponsors:
    # tier1 is top, anycont is bottom (refer to sponsorship packages)
    tier1:
      - logo:        "/images/gsa_logo.png"
        name:        "CMU Graduate Student Assembly"
        url:         "http://www.cmu.edu/stugov/gsa"
      - logo:        "/images/cmuphysics_logo.png"
        name:        "Physics Department at CMU"
        url:         "http://www.cmu.edu/physics"

  info:
    # yo this is the info section what up 

  faq:
    - question:      "What is a hackathon?"
      answer:        >
        A hackathon is an invention marathon. Participants come together to solve interesting problems and create software in the span of a few days.
    - question:      "How much does it cost?"
      answer:        >
        $0. We will also cater all meals for the duration of the event.
    - question:      "Am I eligible to attend"
      answer:        >
        Students at any level, as well as postdocs and faculty members, from any department are welcome to attend. 
    - question:      "What background do I need to have to attend?"
      answer:        >
        We encourage you to attend HTU even if you do not have a physics background, as long as you're interested in working on physics-related problems. HTU will focus on using data analysis and theory to solve physics problems, so skillsets in computer science, statistics, machine learning, math, etc. are very appropriate. We would also encourage you to attend if you're just interested in learning about applying any of these topics to physics problems.
    - question:      "Where is the event?"
      answer:        >
        The event is being hosted on CMU's campus, in Wean Hall 7316. Teams may also use other rooms on campus, but all major events/catering will happen in 7316
    - question:      "How big are the teams?"
      answer:        >
        There are no restrictions on the number of members in a team.
    - question:      "Do you offer travel reimbursement?"
      answer:        >
        We cannot offer travel reimbursements at this point.
    - question:      "Do I have to come with teammates?"
      answer:        >
        There is a team-forming session at the start of the first day so feel free to come along on your own or with friends.
    - question:      "I can't think of a problem to work on, can you help?"
      answer:        >
        Absolutely! We'll aggregate a list of interesting problems to work on. We will also have physics datasets made available. In addition, you can hear other participants' ideas and join a team that interests you. If you're still feeling unsure, [drop us a message](mailto:halmouba@andrew.cmu.edu) and we'll do our best to help!
    - question:      "I have a question that's not answered here, how can I get in touch?"
      answer:        >
        [Drop us a message!](mailto:halmouba@andrew.cmu.edu)

  schedule:
    Friday:
      - text:        "Start of registration"
        start:       "14:30"
      - text:        "Intro & Reception (Piada catering)"
        start:       "16:30"
        end:         "17:30"
      - text:        "Idea pitches & team formation"
        start:       "17:30"
        end:         "18:30"
      - text:        "Kick-off"
        start:       "18:30"
    Saturday:
      - text:        "Breakfast"
        start:       "08:00"
        end:         "10:00"
      - text:        "Lunch (Chipotle)"
        start:       "12:00"
        end:         "13:00"
      - text:        "Secret fun event"
        start:       "14:00"
        end:         "15:00"
      - text:        "Dinner (Choolaah)"
        start:       "18:00"
        end:         "19:00"
    Sunday:
      - text:        "Breakfast"
        start:       "08:00"
        end:         "10:00"
      - text:        "Lunch (Aladdin)"
        start:       "12:00"
        end:         "13:00"
      - text:        "Final presentations & wrap-up"
        start:       "14:00"
        end:         "15:30"

markdown:            kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
